export const timezoneToCountryCode = {
  "Pacific/Midway": "US",
  "Pacific/Niue": "NU",
  "Pacific/Pago_Pago": "AS",
  "Pacific/Honolulu": "US",
  "America/Anchorage": "US",
  "America/Los_Angeles": "US",
  "America/Vancouver": "CA",
  "America/Tijuana": "MX",
  "America/Denver": "US",
  "America/Phoenix": "US",
  "America/Chicago": "US",
  "America/Mexico_City": "MX",
  "America/New_York": "US",
  "America/Toronto": "CA",
  "America/Halifax": "CA",
  "America/Sao_Paulo": "BR",
  "Atlantic/Azores": "PT",
  "Europe/London": "GB",
  "Europe/Dublin": "IE",
  "Europe/Lisbon": "PT",
  "Europe/Paris": "FR",
  "Europe/Brussels": "BE",
  "Europe/Berlin": "DE",
  "Europe/Rome": "IT",
  "Europe/Madrid": "ES",
  "Europe/Zurich": "CH",
  "Europe/Prague": "CZ",
  "Europe/Vienna": "AT",
  "Europe/Warsaw": "PL",
  "Europe/Stockholm": "SE",
  "Europe/Athens": "GR",
  "Europe/Bucharest": "RO",
  "Europe/Istanbul": "TR",
  "Africa/Cairo": "EG",
  "Africa/Johannesburg": "ZA",
  "Asia/Jerusalem": "IL",
  "Asia/Riyadh": "SA",
  "Asia/Dubai": "AE",
  "Asia/Karachi": "PK",
  "Asia/Kolkata": "IN",
  "Asia/Calcutta": "IN",
  "Asia/Dhaka": "BD",
  "Asia/Bangkok": "TH",
  "Asia/Kuala_Lumpur": "MY",
  "Asia/Singapore": "SG",
  "Asia/Manila": "PH",
  "Asia/Tokyo": "JP",
  "Asia/Seoul": "KR",
  "Asia/Hong_Kong": "HK",
  "Asia/Shanghai": "CN",
  "Asia/Taipei": "TW",
  "Asia/Jakarta": "ID",
  "Australia/Sydney": "AU",
  "Australia/Melbourne": "AU",
  "Australia/Brisbane": "AU",
  "Australia/Perth": "AU",
  "Pacific/Auckland": "NZ",
  "Pacific/Fiji": "FJ",
  "Pacific/Tongatapu": "TO",
  "Pacific/Apia": "WS",
  "Pacific/Guam": "GU",
  "Pacific/Port_Moresby": "PG",
  "Antarctica/McMurdo": "AQ",
  "Europe/Moscow": "RU",
  "Europe/Kiev": "UA",
  "Europe/Belgrade": "RS",
  "Europe/Amsterdam": "NL",
  "Europe/Copenhagen": "DK",
  "Europe/Helsinki": "FI",
  "Asia/Yerevan": "AM",
  "Asia/Tbilisi": "GE",
  "Asia/Baku": "AZ",
  "Asia/Almaty": "KZ",
  "Asia/Aqtobe": "KZ",
  "Asia/Novosibirsk": "RU",
  "Asia/Krasnoyarsk": "RU",
  "Asia/Vladivostok": "RU",
  "Asia/Magadan": "RU",
  "Indian/Mauritius": "MU",
  "Indian/Maldives": "MV",
  "Indian/Reunion": "RE",
  "Indian/Chagos": "IO",
  "Pacific/Guadalcanal": "SB",
  "Pacific/Noumea": "NC",
  "Africa/Lagos": "NG",
  "Africa/Nairobi": "KE",
  "Africa/Algiers": "DZ",
  "Africa/Casablanca": "MA",
  "Atlantic/Cape_Verde": "CV",
  "Atlantic/Reykjavik": "IS",
  "Atlantic/South_Georgia": "GS",
  "America/St_Johns": "CA",
  "America/Argentina/Buenos_Aires": "AR",
  "America/Argentina/Mendoza": "AR",
  "America/Caracas": "VE",
  "America/Lima": "PE",
  "America/Bogota": "CO",
  "America/Santiago": "CL",
  "America/Montevideo": "UY",
  "America/La_Paz": "BO",
  "America/Asuncion": "PY",
  "America/Havana": "CU",
  "America/Guatemala": "GT",
  "America/Panama": "PA",
  "America/Costa_Rica": "CR",
  "America/El_Salvador": "SV",
  "America/Tegucigalpa": "HN",
  "America/Kingston": "JM",
  "America/Port-au-Prince": "HT",
  "America/Dominica": "DM",
  "America/Barbados": "BB",
  "America/Belize": "BZ",
  "America/Nassau": "BS",
  "America/Bermuda": "BM",
  "America/Puerto_Rico": "PR",
  "America/Virgin": "VI",
  "Pacific/Easter": "CL",
  "Pacific/Galapagos": "EC",
};


export const CountryInfo = {
  AF: {
    country_name: "Afghanistan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 33.93911,
    longitude: 67.709953,
  },
  AL: {
    country_name: "Albania",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 41.153332,
    longitude: 20.168331,
  },
  DZ: {
    country_name: "Algeria",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 28.033886,
    longitude: 1.659626,
  },
  AS: {
    country_name: "American Samoa",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -14.270972,
    longitude: -170.132217,
  },
  AD: {
    country_name: "Andorra",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 42.546245,
    longitude: 1.601554,
  },
  AO: {
    country_name: "Angola",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -11.202692,
    longitude: 17.873887,
  },
  AI: {
    country_name: "Anguilla",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 18.220554,
    longitude: -63.068615,
  },
  AQ: {
    country_name: "Antarctica",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -75.250973,
    longitude: -0.071389,
  },
  AG: {
    country_name: "Antigua and Barbuda",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 17.060816,
    longitude: -61.796428,
  },
  AR: {
    country_name: "Argentina",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -38.416097,
    longitude: -63.616672,
  },
  AM: {
    country_name: "Armenia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 40.069099,
    longitude: 45.038189,
  },
  AW: {
    country_name: "Aruba",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 12.52111,
    longitude: -69.968338,
  },
  AU: {
    country_name: "Australia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -25.274398,
    longitude: 133.775136,
  },
  AT: {
    country_name: "Austria",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 47.516231,
    longitude: 14.550072,
  },
  AZ: {
    country_name: "Azerbaijan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 40.143105,
    longitude: 47.576927,
  },
  BS: {
    country_name: "Bahamas",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 25.03428,
    longitude: -77.39628,
  },
  BH: {
    country_name: "Bahrain",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 25.930414,
    longitude: 50.637772,
  },
  BD: {
    country_name: "Bangladesh",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 23.684994,
    longitude: 90.356331,
  },
  BB: {
    country_name: "Barbados",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 13.193887,
    longitude: -59.543198,
  },
  BY: {
    country_name: "Belarus",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 53.709807,
    longitude: 27.953389,
  },
  BE: {
    country_name: "Belgium",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 50.503887,
    longitude: 4.469936,
  },
  BZ: {
    country_name: "Belize",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 17.189877,
    longitude: -88.49765,
  },
  BJ: {
    country_name: "Benin",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 9.30769,
    longitude: 2.315834,
  },
  BM: {
    country_name: "Bermuda",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 32.321384,
    longitude: -64.75737,
  },
  BT: {
    country_name: "Bhutan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 27.514162,
    longitude: 90.433601,
  },
  BO: {
    country_name: "Bolivia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -16.290154,
    longitude: -63.588653,
  },
  BQ: {
    country_name: "Bonaire, Sint Eustatius and Saba",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 12.178361,
    longitude: -68.238534,
  },
  BA: {
    country_name: "Bosnia and Herzegovina",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 43.915886,
    longitude: 17.679076,
  },
  BW: {
    country_name: "Botswana",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -22.328474,
    longitude: 24.684866,
  },
  BV: {
    country_name: "Bouvet Island",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -54.423199,
    longitude: 3.413194,
  },
  BR: {
    country_name: "Brazil",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -14.235004,
    longitude: -51.92528,
  },
  IO: {
    country_name: "British Indian Ocean Territory",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -6.343194,
    longitude: 71.876519,
  },
  BN: {
    country_name: "Brunei Darussalam",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 4.535277,
    longitude: 114.727669,
  },
  BG: {
    country_name: "Bulgaria",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 42.733883,
    longitude: 25.48583,
  },
  BF: {
    country_name: "Burkina Faso",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 12.238333,
    longitude: -1.561593,
  },
  BI: {
    country_name: "Burundi",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -3.373056,
    longitude: 29.918886,
  },
  CV: {
    country_name: "Cabo Verde",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 16.002082,
    longitude: -24.013197,
  },
  KH: {
    country_name: "Cambodia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 12.565679,
    longitude: 104.990963,
  },
  CM: {
    country_name: "Cameroon",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 7.369722,
    longitude: 12.354722,
  },
  CA: {
    country_name: "Canada",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 56.130366,
    longitude: -106.346771,
  },
  KY: {
    country_name: "Cayman Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 19.513469,
    longitude: -80.566956,
  },
  CF: {
    country_name: "Central African Republic",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 6.611111,
    longitude: 20.939444,
  },
  TD: {
    country_name: "Chad",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 15.454166,
    longitude: 18.732207,
  },
  CL: {
    country_name: "Chile",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -35.675147,
    longitude: -71.542969,
  },
  CN: {
    country_name: "China",
    currencycode: "MYR",
    currencysymbol: "MYR",
    latitude: 35.86166,
    longitude: 104.195397,
  },
  CX: {
    country_name: "Christmas Island",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -10.447525,
    longitude: 105.690449,
  },
  CC: {
    country_name: "Cocos (Keeling) Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -12.164165,
    longitude: 96.870956,
  },
  CO: {
    country_name: "Colombia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 4.570868,
    longitude: -74.297333,
  },
  KM: {
    country_name: "Comoros",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -11.875001,
    longitude: 43.872219,
  },
  CD: {
    country_name: "Congo, Democratic Republic of the",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -4.038333,
    longitude: 21.758664,
  },
  CG: {
    country_name: "Congo, Republic of the",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -0.228021,
    longitude: 15.827659,
  },
  CK: {
    country_name: "Cook Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -21.236736,
    longitude: -159.777671,
  },
  CR: {
    country_name: "Costa Rica",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 9.748917,
    longitude: -83.753428,
  },
  HR: {
    country_name: "Croatia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 45.1,
    longitude: 15.2,
  },
  CU: {
    country_name: "Cuba",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 21.521757,
    longitude: -77.781167,
  },
  CW: {
    country_name: "Curaçao",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 12.1696,
    longitude: -68.99,
  },
  CY: {
    country_name: "Cyprus",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 35.126413,
    longitude: 33.429859,
  },
  CZ: {
    country_name: "Czech Republic",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 49.817492,
    longitude: 15.472962,
  },
  DK: {
    country_name: "Denmark",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 56.2639,
    longitude: 9.5018,
  },
  DJ: {
    country_name: "Djibouti",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 11.8251,
    longitude: 42.5903,
  },
  DM: {
    country_name: "Dominica",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 15.414999,
    longitude: -61.370976,
  },
  DO: {
    country_name: "Dominican Republic",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 18.7357,
    longitude: -70.1627,
  },
  EC: {
    country_name: "Ecuador",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -1.8312,
    longitude: -78.1834,
  },
  EG: {
    country_name: "Egypt",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 26.820553,
    longitude: 30.802498,
  },
  SV: {
    country_name: "El Salvador",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 13.794185,
    longitude: -88.8965,
  },
  GQ: {
    country_name: "Equatorial Guinea",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 1.6508,
    longitude: 10.2679,
  },
  ER: {
    country_name: "Eritrea",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 15.1794,
    longitude: 39.7823,
  },
  EE: {
    country_name: "Estonia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 58.5953,
    longitude: 25.0136,
  },
  SZ: {
    country_name: "Swaziland",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -26.5225,
    longitude: 31.4659,
  },
  ET: {
    country_name: "Ethiopia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 9.145,
    longitude: 40.4897,
  },
  FK: {
    country_name: "Falkland Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -51.7963,
    longitude: -59.5236,
  },
  FO: {
    country_name: "Faroe Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 61.8926,
    longitude: -6.9118,
  },
  FJ: {
    country_name: "Fiji",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -17.7134,
    longitude: 178.065,
  },
  FI: {
    country_name: "Finland",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 61.9241,
    longitude: 25.7482,
  },
  FR: {
    country_name: "France",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 46.603354,
    longitude: 1.888334,
  },
  GF: {
    country_name: "French Guiana",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 3.9339,
    longitude: -53.1258,
  },
  PF: {
    country_name: "French Polynesia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -17.6797,
    longitude: -149.4068,
  },
  GA: {
    country_name: "Gabon",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -0.8037,
    longitude: 11.6094,
  },
  GM: {
    country_name: "Gambia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 13.4432,
    longitude: -15.3101,
  },
  GE: {
    country_name: "Georgia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 42.3154,
    longitude: 43.3569,
  },
  DE: {
    country_name: "Germany",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 51.1657,
    longitude: 10.4515,
  },
  GH: {
    country_name: "Ghana",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 7.9465,
    longitude: -1.0232,
  },
  GI: {
    country_name: "Gibraltar",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 36.1408,
    longitude: -5.3536,
  },
  GR: {
    country_name: "Greece",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 39.0742,
    longitude: 21.8243,
  },
  GL: {
    country_name: "Greenland",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 71.7069,
    longitude: -42.6043,
  },
  GD: {
    country_name: "Grenada",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 12.2628,
    longitude: -61.6042,
  },
  GP: {
    country_name: "Guadeloupe",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 16.9956,
    longitude: -62.0676,
  },
  GU: {
    country_name: "Guam",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 13.4443,
    longitude: 144.7937,
  },
  GT: {
    country_name: "Guatemala",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 15.7835,
    longitude: -90.2308,
  },
  GG: {
    country_name: "Guernsey",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 49.4657,
    longitude: -2.585,
  },
  GN: {
    country_name: "Guinea",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 9.9456,
    longitude: -9.6966,
  },
  GW: {
    country_name: "Guinea-Bissau",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 11.8037,
    longitude: -15.1804,
  },
  GY: {
    country_name: "Guyana",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 4.8604,
    longitude: -58.9302,
  },
  HT: {
    country_name: "Haiti",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 18.9712,
    longitude: -72.2852,
  },
  HM: {
    country_name: "Heard Island and McDonald Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -53.0818,
    longitude: 73.5041,
  },
  VA: {
    country_name: "Holy See",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 41.9029,
    longitude: 12.4534,
  },
  HN: {
    country_name: "Honduras",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 13.9094,
    longitude: -83.9513,
  },
  HK: {
    country_name: "Hong Kong",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 22.3193,
    longitude: 114.1694,
  },
  HU: {
    country_name: "Hungary",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 47.1625,
    longitude: 19.5033,
  },
  IS: {
    country_name: "Iceland",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 64.9631,
    longitude: -19.0208,
  },
  IN: {
    country_name: "India",
    currencycode: "INR",
    currencysymbol: "₹",
    latitude: 20.5937,
    longitude: 78.9629,
  },
  ID: {
    country_name: "Indonesia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -0.7893,
    longitude: 113.9213,
  },
  IR: {
    country_name: "Iran",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 32.4279,
    longitude: 53.688,
  },
  IQ: {
    country_name: "Iraq",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 33.2232,
    longitude: 43.6793,
  },
  IE: {
    country_name: "Ireland",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 53.1424,
    longitude: -7.6921,
  },
  IM: {
    country_name: "Isle of Man",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 54.2361,
    longitude: -4.5481,
  },
  IL: {
    country_name: "Israel",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 31.0461,
    longitude: 34.8516,
  },
  IT: {
    country_name: "Italy",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 41.8719,
    longitude: 12.5674,
  },
  JM: {
    country_name: "Jamaica",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 18.1096,
    longitude: -77.2975,
  },
  JP: {
    country_name: "Japan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 36.2048,
    longitude: 138.2529,
  },
  JE: {
    country_name: "Jersey",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 49.2144,
    longitude: -2.1313,
  },
  JO: {
    country_name: "Jordan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 30.5852,
    longitude: 36.2384,
  },
  KZ: {
    country_name: "Kazakhstan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 48.0196,
    longitude: 66.9237,
  },
  KE: {
    country_name: "Kenya",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -1.2921,
    longitude: 36.8219,
  },
  KI: {
    country_name: "Kiribati",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -3.3704,
    longitude: -168.734,
  },
  KP: {
    country_name: "Korea, Democratic People's Republic of",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 40.3399,
    longitude: 127.5101,
  },
  KR: {
    country_name: "Korea, Republic of",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 35.9078,
    longitude: 127.7669,
  },
  KW: {
    country_name: "Kuwait",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 29.3759,
    longitude: 47.9774,
  },
  KG: {
    country_name: "Kyrgyzstan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 41.2044,
    longitude: 74.7661,
  },
  LA: {
    country_name: "Lao People's Democratic Republic",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 19.8563,
    longitude: 102.4955,
  },
  LV: {
    country_name: "Latvia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 56.8796,
    longitude: 24.6032,
  },
  LB: {
    country_name: "Lebanon",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 33.8547,
    longitude: 35.8623,
  },
  LS: {
    country_name: "Lesotho",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -29.6093,
    longitude: 28.2336,
  },
  LR: {
    country_name: "Liberia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 6.4281,
    longitude: -9.4295,
  },
  LY: {
    country_name: "Libya",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 26.3351,
    longitude: 17.2283,
  },
  LI: {
    country_name: "Liechtenstein",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 47.1415,
    longitude: 9.5215,
  },
  LT: {
    country_name: "Lithuania",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 55.1694,
    longitude: 23.8813,
  },
  LU: {
    country_name: "Luxembourg",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 49.6117,
    longitude: 6.13,
  },
  MO: {
    country_name: "Macao",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 22.1987,
    longitude: 113.5439,
  },
  MG: {
    country_name: "Madagascar",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -18.7669,
    longitude: 46.8691,
  },
  MW: {
    country_name: "Malawi",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -13.2543,
    longitude: 34.3015,
  },
  MY: {
    country_name: "Malaysia",
    currencycode: "MYR",
    currencysymbol: "MYR",
    latitude: 4.2105,
    longitude: 101.9758,
  },
  MV: {
    country_name: "Maldives",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 3.2028,
    longitude: 73.2207,
  },
  ML: {
    country_name: "Mali",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 12.6392,
    longitude: -8.0029,
  },
  MT: {
    country_name: "Malta",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 35.9375,
    longitude: 14.3754,
  },
  MH: {
    country_name: "Marshall Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 7.1315,
    longitude: 171.1845,
  },
  MQ: {
    country_name: "Martinique",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 14.6415,
    longitude: -61.0242,
  },
  MR: {
    country_name: "Mauritania",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 21.0079,
    longitude: -10.9408,
  },
  MU: {
    country_name: "Mauritius",
    currencycode: "INR",
    currencysymbol: "₹",
    latitude: -20.3484,
    longitude: 57.5522,
  },
  YT: {
    country_name: "Mayotte",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -12.8275,
    longitude: 45.1662,
  },
  MX: {
    country_name: "Mexico",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 23.6345,
    longitude: -102.5528,
  },
  FM: {
    country_name: "Micronesia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 7.4256,
    longitude: 150.5508,
  },
  MD: {
    country_name: "Moldova",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 47.4116,
    longitude: 28.3699,
  },
  MC: {
    country_name: "Monaco",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 43.7333,
    longitude: 7.4167,
  },
  MN: {
    country_name: "Mongolia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 46.8625,
    longitude: 103.8467,
  },
  ME: {
    country_name: "Montenegro",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 42.7087,
    longitude: 19.3744,
  },
  MS: {
    country_name: "Montserrat",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 16.7425,
    longitude: -62.2181,
  },
  MA: {
    country_name: "Morocco",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 31.7917,
    longitude: -7.0926,
  },
  MZ: {
    country_name: "Mozambique",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -18.6657,
    longitude: 35.5295,
  },
  MM: {
    country_name: "Myanmar",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 21.9139,
    longitude: 95.956,
  },
  NA: {
    country_name: "Namibia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -22.9576,
    longitude: 18.4904,
  },
  NR: {
    country_name: "Nauru",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -0.5228,
    longitude: 166.9315,
  },
  NP: {
    country_name: "Nepal",
    currencycode: "INR",
    currencysymbol: "₹",
    latitude: 28.3949,
    longitude: 84.124,
  },
  NL: {
    country_name: "Netherlands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 52.3676,
    longitude: 4.9041,
  },
  NC: {
    country_name: "New Caledonia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -20.9043,
    longitude: 165.618,
  },
  NZ: {
    country_name: "New Zealand",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -40.9006,
    longitude: 174.886,
  },
  NI: {
    country_name: "Nicaragua",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 12.8654,
    longitude: -85.2072,
  },
  NE: {
    country_name: "Niger",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 17.6078,
    longitude: 8.0817,
  },
  NG: {
    country_name: "Nigeria",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 9.082,
    longitude: 8.6753,
  },
  NU: {
    country_name: "Niue",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -19.0544,
    longitude: -169.8671,
  },
  NF: {
    country_name: "Norfolk Island",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -29.0408,
    longitude: 167.9543,
  },
  MP: {
    country_name: "Northern Mariana Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 17.3308,
    longitude: 145.3847,
  },
  NO: {
    country_name: "Norway",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 60.472,
    longitude: 8.4689,
  },
  OM: {
    country_name: "Oman",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 21.4735,
    longitude: 55.9754,
  },
  PK: {
    country_name: "Pakistan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 30.3753,
    longitude: 69.3451,
  },
  PW: {
    country_name: "Palau",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 7.5149,
    longitude: 134.5825,
  },
  PS: {
    country_name: "Palestine",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 31.9522,
    longitude: 35.2332,
  },
  PA: {
    country_name: "Panama",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 8.538,
    longitude: -80.7821,
  },
  PG: {
    country_name: "Papua New Guinea",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -6.3149,
    longitude: 143.9555,
  },
  PY: {
    country_name: "Paraguay",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -23.4425,
    longitude: -58.4438,
  },
  PE: {
    country_name: "Peru",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -9.19,
    longitude: -75.0152,
  },
  PH: {
    country_name: "Philippines",
    currencycode: "MYR",
    currencysymbol: "MYR",
    latitude: 12.8797,
    longitude: 121.774,
  },
  PN: {
    country_name: "Pitcairn",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -24.7036,
    longitude: -127.4398,
  },
  PL: {
    country_name: "Poland",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 51.9194,
    longitude: 19.1451,
  },
  PT: {
    country_name: "Portugal",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 39.3999,
    longitude: -8.2245,
  },
  PR: {
    country_name: "Puerto Rico",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 18.2208,
    longitude: -66.5901,
  },
  QA: {
    country_name: "Qatar",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 25.276987,
    longitude: 51.520008,
  },
  RE: {
    country_name: "Réunion",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -21.1151,
    longitude: 55.5364,
  },
  RO: {
    country_name: "Romania",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 45.9432,
    longitude: 24.9668,
  },
  RU: {
    country_name: "Russian Federation",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 55.7558,
    longitude: 37.6173,
  },
  RW: {
    country_name: "Rwanda",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -1.9403,
    longitude: 29.8739,
  },
  BL: {
    country_name: "Saint Barthélemy",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 17.9,
    longitude: -62.85,
  },
  SH: {
    country_name: "Saint Helena",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -15.965,
    longitude: -5.7089,
  },
  KN: {
    country_name: "Saint Kitts and Nevis",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 17.357822,
    longitude: -62.783443,
  },
  LC: {
    country_name: "Saint Lucia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 13.9094,
    longitude: -60.9789,
  },
  MF: {
    country_name: "Saint Martin (French part)",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 18.07,
    longitude: -63.1,
  },
  SX: {
    country_name: "Sint Maarten (Dutch part)",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 18.0425,
    longitude: -63.0602,
  },
  PM: {
    country_name: "Saint Pierre and Miquelon",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 46.8852,
    longitude: -56.2711,
  },
  VC: {
    country_name: "Saint Vincent and the Grenadines",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 13.2528,
    longitude: -61.1977,
  },
  WS: {
    country_name: "Samoa",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -13.759,
    longitude: -172.1046,
  },
  SM: {
    country_name: "San Marino",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 43.9333,
    longitude: 12.45,
  },
  ST: {
    country_name: "Sao Tome and Principe",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 0.1864,
    longitude: 6.6131,
  },
  SA: {
    country_name: "Saudi Arabia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 23.8859,
    longitude: 45.0792,
  },
  SN: {
    country_name: "Senegal",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 14.4974,
    longitude: -14.4524,
  },
  RS: {
    country_name: "Serbia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 44.0165,
    longitude: 21.0059,
  },
  SC: {
    country_name: "Seychelles",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -4.6796,
    longitude: 55.4915,
  },
  SL: {
    country_name: "Sierra Leone",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 8.46,
    longitude: -11.7793,
  },
  SG: {
    country_name: "Singapore",
    currencycode: "MYR",
    currencysymbol: "MYR",
    latitude: 1.3521,
    longitude: 103.8198,
  },
  SK: {
    country_name: "Slovakia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 48.669,
    longitude: 19.699,
  },
  SI: {
    country_name: "Slovenia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 46.1511,
    longitude: 14.9955,
  },
  SB: {
    country_name: "Solomon Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -9.7195,
    longitude: 160.0067,
  },
  SO: {
    country_name: "Somalia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 5.1521,
    longitude: 46.1996,
  },
  ZA: {
    country_name: "South Africa",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -30.5595,
    longitude: 22.9375,
  },
  GS: {
    country_name: "South Georgia and the South Sandwich Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -54.4296,
    longitude: -36.5879,
  },
  SS: {
    country_name: "South Sudan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 6.8777,
    longitude: 31.307,
  },
  ES: {
    country_name: "Spain",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 40.4637,
    longitude: -3.7492,
  },
  LK: {
    country_name: "Sri Lanka",
    currencycode: "INR",
    currencysymbol: "₹",
    latitude: 7.8731,
    longitude: 80.7718,
  },
  SD: {
    country_name: "Sudan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 12.8628,
    longitude: 30.2176,
  },
  SR: {
    country_name: "Suriname",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 3.9196,
    longitude: -56.0278,
  },
  SJ: {
    country_name: "Svalbard and Jan Mayen",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 77.97,
    longitude: 23.7133,
  },
  SE: {
    country_name: "Sweden",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 60.1282,
    longitude: 18.6435,
  },
  CH: {
    country_name: "Switzerland",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 46.8182,
    longitude: 8.2275,
  },
  SY: {
    country_name: "Syrian Arab Republic",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 34.8021,
    longitude: 38.9968,
  },
  TW: {
    country_name: "Taiwan, Province of China",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 23.6978,
    longitude: 120.9605,
  },
  TJ: {
    country_name: "Tajikistan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 38.861,
    longitude: 71.2761,
  },
  TZ: {
    country_name: "Tanzania, United Republic of",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -6.1659,
    longitude: 39.2026,
  },
  TH: {
    country_name: "Thailand",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 15.87,
    longitude: 100.9925,
  },
  TG: {
    country_name: "Togo",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 8.6195,
    longitude: 0.8252,
  },
  TK: {
    country_name: "Tokelau",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -9.2,
    longitude: -171.2,
  },
  TO: {
    country_name: "Tonga",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -21.1791,
    longitude: -175.1982,
  },
  TT: {
    country_name: "Trinidad and Tobago",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 10.6918,
    longitude: -61.2225,
  },
  TN: {
    country_name: "Tunisia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 33.8869,
    longitude: 9.5375,
  },
  TR: {
    country_name: "Turkey",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 38.9637,
    longitude: 35.2433,
  },
  TM: {
    country_name: "Turkmenistan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 38.9697,
    longitude: 59.5563,
  },
  TC: {
    country_name: "Turks and Caicos Islands",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 21.694,
    longitude: -71.7979,
  },
  TV: {
    country_name: "Tuvalu",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -7.1095,
    longitude: 179.194,
  },
  UG: {
    country_name: "Uganda",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 1.3733,
    longitude: 32.2903,
  },
  UA: {
    country_name: "Ukraine",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 48.3794,
    longitude: 31.1656,
  },
  AE: {
    country_name: "United Arab Emirates",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 23.4241,
    longitude: 53.8478,
  },
  GB: {
    country_name: "United Kingdom",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 55.3781,
    longitude: -3.436,
  },
  US: {
    country_name: "United States",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 37.0902,
    longitude: -95.7129,
  },
  UY: {
    country_name: "Uruguay",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -32.5228,
    longitude: -55.765,
  },
  UZ: {
    country_name: "Uzbekistan",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 41.3775,
    longitude: 64.585,
  },
  VU: {
    country_name: "Vanuatu",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -15.3767,
    longitude: 167.8231,
  },
  VE: {
    country_name: "Venezuela",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 6.4238,
    longitude: -66.5897,
  },
  VN: {
    country_name: "Viet Nam",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 14.0583,
    longitude: 108.2772,
  },
  WF: {
    country_name: "Wallis and Futuna",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -13.7689,
    longitude: -177.156,
  },
  EH: {
    country_name: "Western Sahara",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 24.2155,
    longitude: -12.885,
  },
  YE: {
    country_name: "Yemen",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: 15.552,
    longitude: 48.5164,
  },
  ZM: {
    country_name: "Zambia",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -13.1339,
    longitude: 27.8493,
  },
  ZW: {
    country_name: "Zimbabwe",
    currencycode: "USD",
    currencysymbol: "US $",
    latitude: -19.0154,
    longitude: 29.1549,
  },
};



export const timezoneCountryMap = {
  "Pacific/Midway": "US",
  "Pacific/Niue": "NU",
  "Pacific/Pago_Pago": "AS",
  "Pacific/Honolulu": "US",
  "America/Anchorage": "US",
  "America/Los_Angeles": "US",
  "America/Vancouver": "CA",
  "America/Tijuana": "MX",
  "America/Denver": "US",
  "America/Phoenix": "US",
  "America/Chicago": "US",
  "America/Mexico_City": "MX",
  "America/New_York": "US",
  "America/Toronto": "CA",
  "America/Halifax": "CA",
  "America/Sao_Paulo": "BR",
  "Atlantic/Azores": "PT",
  "Europe/London": "GB",
  "Europe/Dublin": "IE",
  "Europe/Lisbon": "PT",
  "Europe/Paris": "FR",
  "Europe/Brussels": "BE",
  "Europe/Berlin": "DE",
  "Europe/Rome": "IT",
  "Europe/Madrid": "ES",
  "Europe/Zurich": "CH",
  "Europe/Prague": "CZ",
  "Europe/Vienna": "AT",
  "Europe/Warsaw": "PL",
  "Europe/Stockholm": "SE",
  "Europe/Athens": "GR",
  "Europe/Bucharest": "RO",
  "Europe/Istanbul": "TR",
  "Africa/Cairo": "EG",
  "Africa/Johannesburg": "ZA",
  "Asia/Jerusalem": "IL",
  "Asia/Riyadh": "SA",
  "Asia/Dubai": "AE",
  "Asia/Karachi": "PK",
  "Asia/Kolkata": "IN",
  "Asia/Calcutta": "IN",
  "Asia/Dhaka": "BD",
  "Asia/Bangkok": "TH",
  "Asia/Kuala_Lumpur": "MY",
  "Asia/Singapore": "SG",
  "Asia/Manila": "PH",
  "Asia/Tokyo": "JP",
  "Asia/Seoul": "KR",
  "Asia/Hong_Kong": "HK",
  "Asia/Shanghai": "CN",
  "Asia/Taipei": "TW",
  "Asia/Jakarta": "ID",
  "Australia/Sydney": "AU",
  "Australia/Melbourne": "AU",
  "Australia/Brisbane": "AU",
  "Australia/Perth": "AU",
  "Pacific/Auckland": "NZ",
  "Pacific/Fiji": "FJ",
  "Pacific/Tongatapu": "TO",
  "Pacific/Apia": "WS",
  "Pacific/Guam": "GU",
  "Pacific/Port_Moresby": "PG",
  "Antarctica/McMurdo": "AQ",
  "Europe/Moscow": "RU",
  "Europe/Kiev": "UA",
  "Europe/Belgrade": "RS",
  "Europe/Amsterdam": "NL",
  "Europe/Copenhagen": "DK",
  "Europe/Helsinki": "FI",
  "Asia/Yerevan": "AM",
  "Asia/Tbilisi": "GE",
  "Asia/Baku": "AZ",
  "Asia/Almaty": "KZ",
  "Asia/Aqtobe": "KZ",
  "Asia/Novosibirsk": "RU",
  "Asia/Krasnoyarsk": "RU",
  "Asia/Vladivostok": "RU",
  "Asia/Magadan": "RU",
  "Indian/Mauritius": "MU",
  "Indian/Maldives": "MV",
  "Indian/Reunion": "RE",
  "Indian/Chagos": "IO",
  "Pacific/Guadalcanal": "SB",
  "Pacific/Noumea": "NC",
  "Africa/Lagos": "NG",
  "Africa/Nairobi": "KE",
  "Africa/Algiers": "DZ",
  "Africa/Casablanca": "MA",
  "Atlantic/Cape_Verde": "CV",
  "Atlantic/Reykjavik": "IS",
  "Atlantic/South_Georgia": "GS",
  "America/St_Johns": "CA",
  "America/Argentina/Buenos_Aires": "AR",
  "America/Argentina/Mendoza": "AR",
  "America/Caracas": "VE",
  "America/Lima": "PE",
  "America/Bogota": "CO",
  "America/Santiago": "CL",
  "America/Montevideo": "UY",
  "America/La_Paz": "BO",
  "America/Asuncion": "PY",
  "America/Havana": "CU",
  "America/Guatemala": "GT",
  "America/Panama": "PA",
  "America/Costa_Rica": "CR",
  "America/El_Salvador": "SV",
  "America/Tegucigalpa": "HN",
  "America/Kingston": "JM",
  "America/Port-au-Prince": "HT",
  "America/Dominica": "DM",
  "America/Barbados": "BB",
  "America/Belize": "BZ",
  "America/Nassau": "BS",
  "America/Bermuda": "BM",
  "America/Puerto_Rico": "PR",
  "America/Virgin": "VI",
  "Pacific/Easter": "CL",
  "Pacific/Galapagos": "EC"
};